### ISSUE TITLE
ignore matches between <script> tags

### ISSUE THREAD

**Issue by Mikaro** [wshawn/ObfuscateEmail#2]
Hi,

I need not be obfuscate if the email address is in javascript code

I have to send the email to Zopim
https://api.zopim.com/files/meshim/widget/controllers/LiveChatAPI-js.html

**Comment by wshawn** [comment]
Sadly, even that has to be protected, bots look for email addresses throughout the source code of a page even in JavaScript.

The purpose of the plugin is to protect all email addresses on the site without regard to the implementation.

I would have to assume your implementation is incorrect or needs changed. As I do not know anything about zopim I have asked them to get involved.

Suggestions:
You can use AJAX to fill the field and send the request.

You could also convert the hex and decimal back to text before sending the request to them. JavaScript does have those features.

After chatting with them and using the chat application, I see no reason you are having this issue if you have set up the application per their documentation.

The developers are looking into this on their end.

**Comment by Mikaro** [comment]
Hi Shawn,

thx for reply...

this is my chunk with zopim widget ad script to pre-set user information (user information only if logged)

``` javascript
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
$.src="//v2.zopim.com/?xxxxxxxxxxxxxxxxxxxxxxxxxxxx";z.t=+new Date;$.
type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
</script>
<!--End of Zopim Live Chat Script-->

<script>

[[!Profile]]
$zopim(function() {
$zopim.livechat.setName('[[+fullname]]');
$zopim.livechat.setEmail("[[+email]]");
$zopim.livechat.addTags('Subscription_Plan');
});
</script>
```

with ObfuscateEmail enabled the email is not set in the chat window
instead it works with the plugin disabled

I do not understand how I could solve with ajax

excuse my English

greetings

**Comment by wshawn** [comment]
The vendor wants you to:
*
Thank you so much for clarifying that for me. I believe the issue is with the API he has been using with the zopim script that sets the name and email of the visitor. To confirm this, you can ask him to run the widget script alone without the API and see if it's the API that's causing it.

Best Regards,
Mark Gil Maramo
Customer Advocate | Zopim Chat
*

In other words comment out your Profile call as shown with the hypens:

``` html
[[--!Profile]]
$zopim(function() {
$zopim.livechat.setName('[[+fullname]]');
$zopim.livechat.setEmail("[[+email]]");
$zopim.livechat.addTags('Subscription_Plan');
});
```

**Comment by Mikaro** [comment]
The problem is that: Zopim does not accept an email obfuscated!

$zopim.livechat.setEmail("s&#x68;&#97;wn&#64;&#x73;&#x68;&#97;&#119;&#x6e;&#x77;&#105;&#x6c;&#107;&#x65;&#x72;&#115;&#111;&#110;.&#x63;&#111;&#x6d;");
 Can't work!

I'm looking  a way to prevent the plugin OfuscateEmail hides that email only

**Comment by wshawn** [comment]
zopim is asking you to not send the email that way. Comment out the Profile call as shown above.
And let us know if that is working as it should.

Obfuscate will work on everything as it should. The Vendor is looking at how you are calling the API.

**Comment by wshawn** [comment]
Try this:

``` javascript
<script>
[[!Profile]]
$zopim(function() {
var email = "[[+email:replace=`@==AT`]]";
$zopim.livechat.setName('[[+fullname]]');
$zopim.livechat.setEmail(email.replace (/at/i, "@"));
$zopim.livechat.addTags('Subscription_Plan');
});
</script>
```

I replaced the @ symbol and put it back when the email is sent to the vendor.

**Comment by Mikaro** [comment]
Thx Shawn
ingenious solution!

**Comment by wshawn** [comment]
Glad you like it.
