### ISSUE TITLE
@media rules are obfuscated, too

### ISSUE THREAD

**Issue by jivedog70** [wshawn/ObfuscateEmail#4]
I applied this snippet to a site using critical path css in the head; it obfuscates @media rules.

**Comment by wshawn** [comment]
In my opinion, those should be placed in an external css file per https://developer.yahoo.com/blogs/ydn/high-performance-sites-rule-8-javascript-css-external-7205.html and other experts.  It would be highly impractical to filter @print, @media, or @screen as those could be actual components of email addresses.

**Comment by jivedog70** [comment]
That's interesting. In the decade that has passed since that article was written, the number of people using the net has tripled to ~3B, the number of websites have increased from about 100k when the article was posted to [more than 1B today](http://www.internetlivestats.com/total-number-of-websites/), and sites have increased in complexity and size. Average page size currently stands [north of 2MBs](http://httparchive.org/interesting.php).

Given these conditions, identifying and injecting critical path CSS is now a common development practice, and doing so is also part of [Google's performance recommendations](https://developers.google.com/web/fundamentals/performance/critical-rendering-path/render-blocking-css).

Your point about @print, @media, etc. as email patterns -- yes, that's possible. Is it likely? I guess you could argue as much, but as rationale for not modernizing this snippet, that seems thin. The number of sites driven by ModX is insignificant relative to the general web, so it makes sense that the use case I posted hasn't shown up. Nonetheless, it would be great if this snippet was updated to reflect the state of the web today.

In the scenario where CSS declarations are also present as email patterns, perhaps an input from the user to ignore these patterns solves the problem. I don't know how the snippet works specifically, other than that it looks at the site's code en masse, but I've also never once heard a developer state that something is impossible. ;)

**Comment by wshawn** [comment]
I didn't say it was impossible. I just don't see how modifying it adds value to the package, especially as it is the best email obfuscater for MODX as is. At least from the ones I have had a chance to test it against.

By the way, this is a plugin, which doesn't exactly make it easy for people to pass parameters. 

As it stands, people can install it and forget about it.

Your Google link also shows css as external files. Most css and other static content are pulled from CDNs these days.

Just move your css to external files.
